# Permalinks
permalink:           pretty

# Setup
title:               'spencer.codes'
tagline:             '&& writes about it'
description:         'Full stack engineer currently into: React && Redux && Python && Flask && PostgreSQL && ğŸ’€âš°ğŸ´'
url:                 http://spencer.codes
baseurl:             ''
gems: [jekyll-paginate]
paginate:            5
paginate_path: "page:num"

# About/contact
author:
  name:              spencer liechty
  url:               https://github.com/spncrlkt
  email:             spencerliechty@gmail.com

# Custom vars
version:             1.0.0
